export const REQUEST = 'REQUEST';
export const FAILURE = 'FAILURE';

export const REGISTER_SUCCESS = 'REGISTER_SUCCESS';

export const LOGIN_SUCCESS = 'LOGIN_SUCCESS';

export const EDIT_SUCCESS = 'EDIT_SUCCESS';

export const MISSION_SUCCESS = 'MISSION_SUCCESS';

export const PROJECT_SUCCESS = 'PROJECT_SUCCESS';

export const GET_MISSION_SUCCESS = 'GET_MISSION_SUCCESS';

export const DELETE_MISSION_SUCCESS = 'DELETE_MISSION_SUCCESS';

export const UPDATE_SUCCESS = 'UPDATE_SUCCESS';

export const GET_PROJECT_SUCCESS = 'GET_PROJECT_SUCCESS';

export const UPDATE_PROJECT_SUCCESS = 'UPDATE_PROJECT_SUCCESS';

export const GET_DATA_SUCCESS = 'GET_DATA_SUCCESS';

export const LOGOUT = 'LOGOUT';
